/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    destinations: Destination;
    trips: Trip;
    blogs: Blog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    trips: TripsSelect<false> | TripsSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images and media assets for journeys, destinations, and journal articles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive text for accessibility and SEO (required).
   */
  alt: string;
  /**
   * Optional caption or photography credit.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Categories for organizing journeys and journal articles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Unique URL path identifier. Auto-generated from title/name if left empty.
   */
  slug?: string | null;
  /**
   * Whether this category applies to trips or journal articles.
   */
  type: 'trip' | 'blog';
  /**
   * Brief description of what this category covers.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Himalayan regions and destinations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  name: string;
  /**
   * Unique URL path identifier. Auto-generated from title/name if left empty.
   */
  slug?: string | null;
  /**
   * Key ranges or passes (e.g. "Annapurna · Dhaulagiri · Mustang")
   */
  kicker?: string | null;
  /**
   * Two-digit index (e.g. "01", "02")
   */
  number?: string | null;
  tile?: ('far' | 'mid' | 'west' | 'cent' | 'east') | null;
  size?: ('standard' | 'feature') | null;
  description: string;
  /**
   * Recommended seasons/months (e.g. "Autumn (Oct–Nov) · Spring (Mar–May)")
   */
  bestTimeToVisit?: string | null;
  attractions?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  heroImage?: (number | null) | Media;
  /**
   * Fallback path (e.g. "/images/region-far-west.webp") if no upload selected
   */
  imageUrl?: string | null;
  /**
   * CSS object-position (e.g. "center 42%")
   */
  imagePosition?: string | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Trips linked to this destination.
   */
  relatedTrips?: (number | Trip)[] | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  canonicalURL?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Himalayan trekking and expedition journeys.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips".
 */
export interface Trip {
  id: number;
  title: string;
  /**
   * Unique URL path identifier. Auto-generated from title/name if left empty.
   */
  slug?: string | null;
  /**
   * Geographic location (e.g. "Khumbu, Nepal")
   */
  location?: string | null;
  /**
   * Linked destination region in the CMS.
   */
  destination?: (number | null) | Destination;
  /**
   * Short region name used for frontend filter chips (e.g. "Everest", "Annapurna", "Mustang").
   */
  destinationName?: string | null;
  /**
   * Brief 1-2 sentence overview for cards and teasers.
   */
  shortDescription?: string | null;
  /**
   * Detailed story and description of this journey.
   */
  description: string;
  tripType?: ('Trek' | 'Expedition' | 'Cultural') | null;
  /**
   * Featured trips are prioritized at the top of listings.
   */
  featured?: boolean | null;
  /**
   * Human-readable duration (e.g. "15 days")
   */
  duration?: string | null;
  /**
   * Integer days for sorting (e.g. 15)
   */
  durationDays?: number | null;
  /**
   * Base price per person in USD (e.g. 1490)
   */
  price: number;
  currency?: string | null;
  difficulty: 'Easy' | 'Moderate' | 'Challenging';
  groupSize?: string | null;
  seasons?: ('Spring' | 'Summer' | 'Autumn' | 'Winter')[] | null;
  primeSeason?: ('Spring' | 'Summer' | 'Autumn' | 'Winter') | null;
  /**
   * Departure window (e.g. "Mar · Apr · Oct · Nov")
   */
  departures?: string | null;
  /**
   * Peak altitude (e.g. "5,364 m")
   */
  elevation?: string | null;
  /**
   * Editorial highlight quote (e.g. "First light on the icefall from the ridge above Gorak Shep")
   */
  highlight?: string | null;
  /**
   * e.g. "4 places in October"
   */
  availability?: string | null;
  bestTimeToVisit?: string | null;
  itinerary?:
    | {
        day: number;
        title: string;
        description?: string | null;
        altitude?: string | null;
        accommodation?: string | null;
        meals?: string | null;
        id?: string | null;
      }[]
    | null;
  inclusions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  exclusions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  featuredImage?: (number | null) | Media;
  /**
   * Fallback path (e.g. "/images/trip-everest.webp")
   */
  imageUrl?: string | null;
  imagePosition?: string | null;
  alt?: string | null;
  gallery?:
    | {
        image?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  canonicalURL?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Field notes, guides, and stories from the trail.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  /**
   * Unique URL path identifier. Auto-generated from title/name if left empty.
   */
  slug?: string | null;
  /**
   * Brief overview displayed on cards and drawer intros.
   */
  excerpt: string;
  /**
   * Full rich-text content managed via the Lexical editor.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * For guides with complex tables or verbatim verification.
   */
  rawMarkdown?: string | null;
  featuredImage?: (number | null) | Media;
  /**
   * Fallback path (e.g. "/images/journal-kathmandu.webp")
   */
  imageUrl?: string | null;
  alt?: string | null;
  author?: string | null;
  category?: (number | null) | Category;
  /**
   * Display label for category chip (e.g. "Practical Guide", "Culture").
   */
  categoryName?: string | null;
  readTime?: string | null;
  publishedDate?: string | null;
  /**
   * Highlights article as a featured premium deep-dive guide.
   */
  premium?: boolean | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  ogImage?: (number | null) | Media;
  canonicalURL?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null)
    | ({
        relationTo: 'trips';
        value: number | Trip;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kicker?: T;
  number?: T;
  tile?: T;
  size?: T;
  description?: T;
  bestTimeToVisit?: T;
  attractions?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  heroImage?: T;
  imageUrl?: T;
  imagePosition?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  relatedTrips?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  canonicalURL?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips_select".
 */
export interface TripsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  location?: T;
  destination?: T;
  destinationName?: T;
  shortDescription?: T;
  description?: T;
  tripType?: T;
  featured?: T;
  duration?: T;
  durationDays?: T;
  price?: T;
  currency?: T;
  difficulty?: T;
  groupSize?: T;
  seasons?: T;
  primeSeason?: T;
  departures?: T;
  elevation?: T;
  highlight?: T;
  availability?: T;
  bestTimeToVisit?: T;
  itinerary?:
    | T
    | {
        day?: T;
        title?: T;
        description?: T;
        altitude?: T;
        accommodation?: T;
        meals?: T;
        id?: T;
      };
  inclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  exclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  featuredImage?: T;
  imageUrl?: T;
  imagePosition?: T;
  alt?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  canonicalURL?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  rawMarkdown?: T;
  featuredImage?: T;
  imageUrl?: T;
  alt?: T;
  author?: T;
  category?: T;
  categoryName?: T;
  readTime?: T;
  publishedDate?: T;
  premium?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  canonicalURL?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}