function getEnv(key) {
  if (typeof globalThis !== 'undefined' && globalThis.process && globalThis.process.env && globalThis.process.env[key]) {
    return globalThis.process.env[key]
  }
  try {
    const metaEnv = new Function('try { return import.meta.env } catch(e) { return null }')()
    if (metaEnv && metaEnv[key]) return metaEnv[key]
  } catch {
    // fallback
  }
  return ''
}

const PAYLOAD_URL = (getEnv('VITE_PAYLOAD_URL') || '').replace(/\/+$/, '')

/**
 * Resolves an image URL from either a Payload Media object or a static path.
 * Supports responsive image size variants (thumbnail, card, hero) generated by Payload.
 *
 * @param {Object|string|null} media - The media object from Payload or string path.
 * @param {'thumbnail'|'card'|'hero'|null} [size='card'] - Preferred responsive size.
 * @param {string} [fallback=''] - Fallback URL if media is absent.
 * @returns {string} Fully resolvable image URL.
 */
export function getMediaUrl(media, size = 'card', fallback = '') {
  if (!media) return fallback

  if (typeof media === 'string') {
    if (media.startsWith('http://') || media.startsWith('https://')) return media
    if (media.startsWith('/media/') && PAYLOAD_URL) return `${PAYLOAD_URL}${media}`
    return media
  }

  const candidateUrl =
    (size && media.sizes && media.sizes[size] && media.sizes[size].url) ||
    media.url ||
    media.imageUrl ||
    fallback

  if (!candidateUrl) return fallback
  if (candidateUrl.startsWith('http://') || candidateUrl.startsWith('https://')) return candidateUrl
  if (PAYLOAD_URL && candidateUrl.startsWith('/')) return `${PAYLOAD_URL}${candidateUrl}`
  return candidateUrl
}

/**
 * Returns accessible alt text from a media object or fallback.
 */
export function getMediaAlt(media, fallback = '') {
  if (!media || typeof media === 'string') return fallback
  return media.alt || media.title || fallback
}
