/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    trips: Trip;
    destinations: Destination;
    departures: Departure;
    posts: Post;
    categories: Category;
    pages: Page;
    authors: Author;
    reviews: Review;
    enquiries: Enquiry;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    trips: {
      departures: 'departures';
      reviews: 'reviews';
    };
    destinations: {
      trips: 'trips';
    };
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    trips: TripsSelect<false> | TripsSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    departures: DeparturesSelect<false> | DeparturesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips".
 */
export interface Trip {
  id: number;
  /**
   * e.g. "Everest Base Camp"
   */
  title: string;
  /**
   * One or two sentences. Used on cards, in search results, and as the SEO description fallback.
   */
  summary: string;
  /**
   * The single image everyone carries home: "First light on the icefall from the ridge above Gorak Shep".
   */
  highlight: string;
  /**
   * Long-form "about this trek" copy for the detail page.
   */
  overview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  destination: number | Destination;
  /**
   * Human-readable: "Khumbu, Nepal".
   */
  location: string;
  durationDays: number;
  difficulty: 'easy' | 'moderate' | 'challenging' | 'strenuous';
  tripType: 'trek' | 'tour' | 'expedition' | 'peak';
  /**
   * Metres. Formatted for display in code.
   */
  maxAltitudeMetres: number;
  /**
   * Every season this trip can run in.
   */
  seasons: ('spring' | 'summer' | 'autumn' | 'winter')[];
  /**
   * The one you would recommend.
   */
  primeSeason: 'spring' | 'summer' | 'autumn' | 'winter';
  groupSizeMax: number;
  /**
   * Guides to travellers.
   */
  guideRatio?: string | null;
  minimumAge?: number | null;
  featured?: boolean | null;
  showInTrekRail?: boolean | null;
  /**
   * Lower sorts first.
   */
  railOrder?: number | null;
  /**
   * One row per day. Day numbers come from the row order — just drag to reorder.
   */
  itinerary?:
    | {
        /**
         * e.g. "Phakding to Namche Bazaar"
         */
        title: string;
        altitudeMetres?: number | null;
        /**
         * "6 hours", "3–4 hours", "No walking".
         */
        walkingHours?: string | null;
        distanceKm?: number | null;
        ascentMetres?: number | null;
        /**
         * "Panorama Lodge, Namche Bazaar"
         */
        accommodation?: string | null;
        meals?: ('breakfast' | 'lunch' | 'dinner')[] | null;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Up to four photos for this day. They auto-slide in the accordion — and must stay lazy-loaded, since a 17-day trek is 68 images that are mostly hidden.
         */
        gallery?: (number | Media)[] | null;
        isAcclimatisationDay?: boolean | null;
        id?: string | null;
      }[]
    | null;
  routeMap?: {
    image?: (number | null) | Media;
    caption?: string | null;
    legend?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Per person, twin share, in the currency beside it. Whole units — no decimals.
   */
  basePrice: number;
  currency: 'USD' | 'EUR' | 'GBP' | 'AUD';
  depositPercent?: number | null;
  /**
   * Flat amount, same currency as above.
   */
  singleSupplement?: number | null;
  privateSurchargePercent?: number | null;
  /**
   * Optional per-head discounts by group size. Leave empty to charge the base price for everyone.
   */
  groupPricing?:
    | {
        minTravellers: number;
        maxTravellers?: number | null;
        pricePerPerson: number;
        id?: string | null;
      }[]
    | null;
  departures?: {
    docs?: (number | Departure)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  includes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  excludes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  packingList?:
    | {
        title: string;
        note?: string | null;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  essentialInfo?:
    | {
        title: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Restricted-area and conservation permits this trip requires.
   */
  permits?:
    | {
        name: string;
        handledByUs?: boolean | null;
        id?: string | null;
      }[]
    | null;
  heroImage: {
    /**
     * Landscape crop. Used from 768px up.
     */
    desktop: number | Media;
    /**
     * Optional portrait crop for phones. Falls back to the desktop image.
     */
    mobile?: (number | null) | Media;
    /**
     * CSS object-position, e.g. "center 42%". Only needed when the media focal point is not enough.
     */
    objectPosition?: string | null;
  };
  /**
   * The crop used on grids, rails and search results.
   */
  cardImage: number | Media;
  gallery?: (number | Media)[] | null;
  leadGuide?: (number | null) | Author;
  relatedTrips?: (number | Trip)[] | null;
  relatedPosts?: (number | Post)[] | null;
  reviews?: {
    docs?: (number | Review)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * The URL segment for this document. Auto-filled from the title. Changing it after publishing breaks existing links — add a redirect if you do.
   */
  slug: string;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  /**
   * e.g. "Far West"
   */
  title: string;
  /**
   * Sub-line: "Kanjakali · Api Himal · Khaptad"
   */
  kicker: string;
  /**
   * Lower sorts first.
   */
  displayOrder: number;
  tileSize?: ('feature' | 'standard') | null;
  /**
   * The paragraph on the bento tile and the region explorer.
   */
  summary: string;
  /**
   * Long-form copy for the destination landing page.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage: {
    /**
     * Landscape crop. Used from 768px up.
     */
    desktop: number | Media;
    /**
     * Optional portrait crop for phones. Falls back to the desktop image.
     */
    mobile?: (number | null) | Media;
    /**
     * CSS object-position, e.g. "center 42%". Only needed when the media focal point is not enough.
     */
    objectPosition?: string | null;
  };
  /**
   * Square-ish crop for grid tiles and nav menus.
   */
  cardImage: number | Media;
  gallery?: (number | Media)[] | null;
  /**
   * The animated counters on the destinations page.
   */
  stats?:
    | {
        value: number;
        /**
         * "+", "%", "m"…
         */
        suffix?: string | null;
        label: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  bestSeasons: ('spring' | 'summer' | 'autumn' | 'winter')[];
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Every trip assigned to this region. Edit the trip to move it.
   */
  trips?: {
    docs?: (number | Trip)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * The URL segment for this document. Auto-filled from the title. Changing it after publishing breaks existing links — add a redirect if you do.
   */
  slug: string;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every image and video on the site. Alt text is required — it is read aloud by screen readers and it is SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe what is in the photo for someone who cannot see it. "Prayer flags above Phoksundo lake" — not "image1".
   */
  alt: string;
  /**
   * Optional visible caption, shown under the image where the layout supports it.
   */
  caption?: string | null;
  /**
   * Photographer or source.
   */
  credit?: string | null;
  licence?: ('owned' | 'stock' | 'cc' | 'guest') | null;
  /**
   * Where it was taken. Used for photo credits and internal search.
   */
  location?: string | null;
  blurDataUrl?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    heroMobile?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every bookable date. Operations can edit these without touching trip content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departures".
 */
export interface Departure {
  id: number;
  trip: number | Trip;
  startDate: string;
  /**
   * Derived from the trip duration.
   */
  endDate?: string | null;
  spotsTotal: number;
  spotsRemaining: number;
  /**
   * Derived from places remaining. Set to Cancelled to pull a date from sale regardless of capacity.
   */
  status: 'available' | 'limited' | 'sold-out' | 'cancelled';
  /**
   * Overrides the trip base price for this date. Leave empty to inherit.
   */
  price?: number | null;
  /**
   * Runs even if it does not fill.
   */
  guaranteed?: boolean | null;
  isPrivate?: boolean | null;
  /**
   * Shown on the calendar, e.g. "Festival dates — book early".
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * e.g. "Lead mountain guide · 19 Himalayan seasons"
   */
  role: string;
  /**
   * Fallback avatar when no photo is set. Derived from the name if left blank.
   */
  initials?: string | null;
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Languages this guide leads in. Press enter between each.
   */
  languages?: string[] | null;
  yearsGuiding?: number | null;
  /**
   * The URL segment for this document. Auto-filled from the title. Changing it after publishing breaks existing links — add a redirect if you do.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Teaser for cards, the journal index, and the SEO description fallback.
   */
  excerpt: string;
  heroImage: number | Media;
  /**
   * The article body. Use H2/H3 for structure — they become the on-page contents list and the heading hierarchy search engines read.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  categories: (number | Category)[];
  authors: (number | Author)[];
  /**
   * Rendered as "Journeys mentioned in this article" — the highest-converting module on a travel blog. Always fill it in.
   */
  relatedTrips?: (number | Trip)[] | null;
  relatedPosts?: (number | Post)[] | null;
  /**
   * Pins to the top of the journal index.
   */
  featured?: boolean | null;
  /**
   * Minutes. Calculated from the body on every save.
   */
  readingTime?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * The URL segment for this document. Auto-filled from the title. Changing it after publishing breaks existing links — add a redirect if you do.
   */
  slug: string;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Shown at the top of the category archive, and used as its SEO text.
   */
  description?: string | null;
  /**
   * The URL segment for this document. Auto-filled from the title. Changing it after publishing breaks existing links — add a redirect if you do.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  name: string;
  /**
   * "London, UK"
   */
  location: string;
  /**
   * Avatar fallback when there is no photo.
   */
  initials?: string | null;
  quote: string;
  rating: number;
  travelledOn: string;
  /**
   * Pin to the homepage voices rail.
   */
  featured?: boolean | null;
  trip?: (number | null) | Trip;
  photo?: (number | null) | Media;
  /**
   * Only verified reviews feed aggregateRating structured data. Do not tick this for anything you cannot evidence — fabricated review markup gets rich results suppressed sitewide.
   */
  verified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout: (
    | HeroBlock
    | RichTextBlock
    | MediaBlock
    | MarqueeBlock
    | StatsBlock
    | DestinationBentoBlock
    | TripRailBlock
    | TripGridBlock
    | ItineraryShowcaseBlock
    | InclusionsBlock
    | SeasonMatrixBlock
    | TestimonialsBlock
    | PostFeedBlock
    | GalleryBlock
    | FAQBlock
    | CTABlock
    | EnquiryFormBlock
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * The URL segment for this document. Auto-filled from the title. Changing it after publishing breaks existing links — add a redirect if you do.
   */
  slug: string;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  variant: 'cinematic' | 'parallax' | 'editorial';
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  background: {
    /**
     * Landscape crop. Used from 768px up.
     */
    desktop: number | Media;
    /**
     * Optional portrait crop for phones. Falls back to the desktop image.
     */
    mobile?: (number | null) | Media;
    /**
     * CSS object-position, e.g. "center 42%". Only needed when the media focal point is not enough.
     */
    objectPosition?: string | null;
  };
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'trips';
                value: number | Trip;
              } | null)
            | ({
                relationTo: 'destinations';
                value: number | Destination;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Percentage of dark overlay. Raise it when the headline is hard to read against the photo.
   */
  overlayOpacity?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Prose caps the line length at around 70 characters. Use it for anything anyone is expected to actually read.
   */
  width: 'prose' | 'wide' | 'full';
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  image: number | Media;
  caption?: string | null;
  size: 'full' | 'inset' | 'half';
  /**
   * Only ever tick this for an image visible without scrolling. Eager-loading a mid-page photo competes with the hero and makes LCP worse, not better.
   */
  priority?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'media';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MarqueeBlock".
 */
export interface MarqueeBlock {
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  speed: 'slow' | 'medium' | 'fast';
  theme: 'dark' | 'light';
  id?: string | null;
  blockName?: string | null;
  blockType: 'marquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  heading?: string | null;
  items?:
    | {
        /**
         * The number only — it counts up to this.
         */
        value: number;
        /**
         * "+", "%", "m", "k"…
         */
        suffix?: string | null;
        label: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Count up when the band scrolls into view. Automatically disabled for visitors with prefers-reduced-motion.
   */
  animate?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DestinationBentoBlock".
 */
export interface DestinationBentoBlock {
  heading?: string | null;
  intro?: string | null;
  /**
   * Automatic respects each destination's own display order and tile size, so adding a region needs no page edit.
   */
  source: 'auto' | 'manual';
  destinations?: (number | Destination)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'destinationBento';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TripRailBlock".
 */
export interface TripRailBlock {
  heading?: string | null;
  intro?: string | null;
  /**
   * Automatic uses every trip with "Show in the Trails worth taking rail" ticked, ordered by its rail order.
   */
  source: 'auto' | 'manual';
  trips?: (number | Trip)[] | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tripRail';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TripGridBlock".
 */
export interface TripGridBlock {
  heading?: string | null;
  intro?: string | null;
  source: 'auto' | 'manual';
  filters?: {
    destinations?: (number | Destination)[] | null;
    difficulty?: ('easy' | 'moderate' | 'challenging' | 'strenuous')[] | null;
    seasons?: ('spring' | 'summer' | 'autumn' | 'winter')[] | null;
    featuredOnly?: boolean | null;
    limit?: number | null;
  };
  trips?: (number | Trip)[] | null;
  showFilters?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tripGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ItineraryShowcaseBlock".
 */
export interface ItineraryShowcaseBlock {
  heading?: string | null;
  intro?: string | null;
  source: 'trip' | 'manual';
  trip?: (number | null) | Trip;
  days?:
    | {
        title: string;
        altitudeMetres?: number | null;
        walkingHours?: string | null;
        body?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'itineraryShowcase';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InclusionsBlock".
 */
export interface InclusionsBlock {
  heading?: string | null;
  intro?: string | null;
  items?:
    | {
        title: string;
        body: string;
        /**
         * Drawn from the icon set — no uploads needed.
         */
        icon?: ('guide' | 'lodging' | 'meals' | 'permits' | 'transport' | 'safety' | 'porter' | 'community') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'inclusions';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeasonMatrixBlock".
 */
export interface SeasonMatrixBlock {
  heading?: string | null;
  intro?: string | null;
  rows?:
    | {
        month: '01' | '02' | '03' | '04' | '05' | '06' | '07' | '08' | '09' | '10' | '11' | '12';
        rating: 'prime' | 'good' | 'mixed' | 'poor';
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'seasonMatrix';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  heading?: string | null;
  source: 'auto' | 'manual';
  /**
   * Limit to reviews of one trip. Leave empty for all trips.
   */
  trip?: (number | null) | Trip;
  minimumRating?: number | null;
  reviews?: (number | Review)[] | null;
  limit?: number | null;
  /**
   * Emit Review JSON-LD. Only verified reviews are ever included, and never an aggregateRating you cannot evidence.
   */
  emitStructuredData?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostFeedBlock".
 */
export interface PostFeedBlock {
  heading?: string | null;
  intro?: string | null;
  source: 'auto' | 'manual';
  /**
   * Leave empty for every category.
   */
  categories?: (number | Category)[] | null;
  posts?: (number | Post)[] | null;
  limit?: number | null;
  layout: 'grid' | 'list' | 'lead';
  id?: string | null;
  blockName?: string | null;
  blockType: 'postFeed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  heading?: string | null;
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  layout: 'grid' | 'masonry' | 'carousel';
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  heading?: string | null;
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Adds FAQPage JSON-LD. Enable on only ONE FAQ block per page — duplicate FAQPage markup gets rich results suppressed.
   */
  emitStructuredData?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock".
 */
export interface CTABlock {
  eyebrow?: string | null;
  heading: string;
  body?: string | null;
  theme: 'dark' | 'light' | 'photo';
  background?: {
    /**
     * Landscape crop. Used from 768px up.
     */
    desktop: number | Media;
    /**
     * Optional portrait crop for phones. Falls back to the desktop image.
     */
    mobile?: (number | null) | Media;
    /**
     * CSS object-position, e.g. "center 42%". Only needed when the media focal point is not enough.
     */
    objectPosition?: string | null;
  };
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'trips';
                value: number | Trip;
              } | null)
            | ({
                relationTo: 'destinations';
                value: number | Destination;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EnquiryFormBlock".
 */
export interface EnquiryFormBlock {
  heading?: string | null;
  intro?: string | null;
  /**
   * Pre-selects this trip on the form. Leave empty for a general enquiry.
   */
  trip?: (number | null) | Trip;
  /**
   * Shown beside the required consent checkbox. Keep it specific — blanket marketing consent bundled into an enquiry is not valid consent.
   */
  consentText: string;
  successMessage: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'enquiryForm';
}
/**
 * Every booking enquiry submitted from the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  country?: string | null;
  trip?: (number | null) | Trip;
  departure?: (number | null) | Departure;
  travellers?: number | null;
  preferredDate?: string | null;
  status?: ('new' | 'contacted' | 'quoted' | 'booked' | 'lost') | null;
  message?: string | null;
  /**
   * Explicit consent to be contacted. Required for GDPR.
   */
  consent: boolean;
  /**
   * Page the enquiry came from.
   */
  source?: string | null;
  /**
   * Never shown to the customer.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  roles: ('admin' | 'editor' | 'operations')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'trips';
        value: number | Trip;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null)
    | ({
        relationTo: 'departures';
        value: number | Departure;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trips_select".
 */
export interface TripsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  highlight?: T;
  overview?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  destination?: T;
  location?: T;
  durationDays?: T;
  difficulty?: T;
  tripType?: T;
  maxAltitudeMetres?: T;
  seasons?: T;
  primeSeason?: T;
  groupSizeMax?: T;
  guideRatio?: T;
  minimumAge?: T;
  featured?: T;
  showInTrekRail?: T;
  railOrder?: T;
  itinerary?:
    | T
    | {
        title?: T;
        altitudeMetres?: T;
        walkingHours?: T;
        distanceKm?: T;
        ascentMetres?: T;
        accommodation?: T;
        meals?: T;
        body?: T;
        gallery?: T;
        isAcclimatisationDay?: T;
        id?: T;
      };
  routeMap?:
    | T
    | {
        image?: T;
        caption?: T;
        legend?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  basePrice?: T;
  currency?: T;
  depositPercent?: T;
  singleSupplement?: T;
  privateSurchargePercent?: T;
  groupPricing?:
    | T
    | {
        minTravellers?: T;
        maxTravellers?: T;
        pricePerPerson?: T;
        id?: T;
      };
  departures?: T;
  includes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  excludes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  packingList?:
    | T
    | {
        title?: T;
        note?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  essentialInfo?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  permits?:
    | T
    | {
        name?: T;
        handledByUs?: T;
        id?: T;
      };
  heroImage?:
    | T
    | {
        desktop?: T;
        mobile?: T;
        objectPosition?: T;
      };
  cardImage?: T;
  gallery?: T;
  leadGuide?: T;
  relatedTrips?: T;
  relatedPosts?: T;
  reviews?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  title?: T;
  kicker?: T;
  displayOrder?: T;
  tileSize?: T;
  summary?: T;
  body?: T;
  heroImage?:
    | T
    | {
        desktop?: T;
        mobile?: T;
        objectPosition?: T;
      };
  cardImage?: T;
  gallery?: T;
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        note?: T;
        id?: T;
      };
  bestSeasons?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  trips?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departures_select".
 */
export interface DeparturesSelect<T extends boolean = true> {
  trip?: T;
  startDate?: T;
  endDate?: T;
  spotsTotal?: T;
  spotsRemaining?: T;
  status?: T;
  price?: T;
  guaranteed?: T;
  isPrivate?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  categories?: T;
  authors?: T;
  relatedTrips?: T;
  relatedPosts?: T;
  featured?: T;
  readingTime?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        media?: T | MediaBlockSelect<T>;
        marquee?: T | MarqueeBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        destinationBento?: T | DestinationBentoBlockSelect<T>;
        tripRail?: T | TripRailBlockSelect<T>;
        tripGrid?: T | TripGridBlockSelect<T>;
        itineraryShowcase?: T | ItineraryShowcaseBlockSelect<T>;
        inclusions?: T | InclusionsBlockSelect<T>;
        seasonMatrix?: T | SeasonMatrixBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        postFeed?: T | PostFeedBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        enquiryForm?: T | EnquiryFormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  background?:
    | T
    | {
        desktop?: T;
        mobile?: T;
        objectPosition?: T;
      };
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  overlayOpacity?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  width?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  size?: T;
  priority?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MarqueeBlock_select".
 */
export interface MarqueeBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  speed?: T;
  theme?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        note?: T;
        id?: T;
      };
  animate?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DestinationBentoBlock_select".
 */
export interface DestinationBentoBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  source?: T;
  destinations?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TripRailBlock_select".
 */
export interface TripRailBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  source?: T;
  trips?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TripGridBlock_select".
 */
export interface TripGridBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  source?: T;
  filters?:
    | T
    | {
        destinations?: T;
        difficulty?: T;
        seasons?: T;
        featuredOnly?: T;
        limit?: T;
      };
  trips?: T;
  showFilters?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ItineraryShowcaseBlock_select".
 */
export interface ItineraryShowcaseBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  source?: T;
  trip?: T;
  days?:
    | T
    | {
        title?: T;
        altitudeMetres?: T;
        walkingHours?: T;
        body?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InclusionsBlock_select".
 */
export interface InclusionsBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  items?:
    | T
    | {
        title?: T;
        body?: T;
        icon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SeasonMatrixBlock_select".
 */
export interface SeasonMatrixBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  rows?:
    | T
    | {
        month?: T;
        rating?: T;
        note?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  source?: T;
  trip?: T;
  minimumRating?: T;
  reviews?: T;
  limit?: T;
  emitStructuredData?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostFeedBlock_select".
 */
export interface PostFeedBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  source?: T;
  categories?: T;
  posts?: T;
  limit?: T;
  layout?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  heading?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  layout?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  emitStructuredData?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CTABlock_select".
 */
export interface CTABlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  theme?: T;
  background?:
    | T
    | {
        desktop?: T;
        mobile?: T;
        objectPosition?: T;
      };
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EnquiryFormBlock_select".
 */
export interface EnquiryFormBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  trip?: T;
  consentText?: T;
  successMessage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  initials?: T;
  photo?: T;
  bio?: T;
  languages?: T;
  yearsGuiding?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  name?: T;
  location?: T;
  initials?: T;
  quote?: T;
  rating?: T;
  travelledOn?: T;
  featured?: T;
  trip?: T;
  photo?: T;
  verified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  country?: T;
  trip?: T;
  departure?: T;
  travellers?: T;
  preferredDate?: T;
  status?: T;
  message?: T;
  consent?: T;
  source?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  licence?: T;
  location?: T;
  blurDataUrl?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        heroMobile?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * The fullscreen navigation. Eight items is already more than anyone reads.
   */
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'trips';
                value: number | Trip;
              } | null)
            | ({
                relationTo: 'destinations';
                value: number | Destination;
              } | null);
          url?: string | null;
          label: string;
        };
        /**
         * Optional dropdown.
         */
        children?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null)
                  | ({
                      relationTo: 'trips';
                      value: number | Trip;
                    } | null)
                  | ({
                      relationTo: 'destinations';
                      value: number | Destination;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title: string;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null)
                  | ({
                      relationTo: 'trips';
                      value: number | Trip;
                    } | null)
                  | ({
                      relationTo: 'destinations';
                      value: number | Destination;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  newsletter?: {
    heading?: string | null;
    body?: string | null;
    ctaLabel?: string | null;
    consentText?: string | null;
  };
  /**
   * Trade body and licence marks — NMA, TAAN, Nepal Tourism Board.
   */
  certifications?:
    | {
        title: string;
        logo?: (number | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Company registration and licence numbers. Shown in the bottom rule.
   */
  legalLine?: string | null;
  legalLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'trips';
                value: number | Trip;
              } | null)
            | ({
                relationTo: 'destinations';
                value: number | Destination;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  /**
   * 1200×630. Used whenever a page has no SEO image of its own.
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * Used in Organization structured data.
   */
  legalName: string;
  email: string;
  phone?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    region?: string | null;
    postalCode?: string | null;
    /**
     * ISO 3166-1 alpha-2.
     */
    country?: string | null;
  };
  socials?:
    | {
        platform: 'instagram' | 'facebook' | 'youtube' | 'tripadvisor' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultCurrency?: ('USD' | 'EUR' | 'GBP' | 'AUD') | null;
  /**
   * Where booking enquiries are sent.
   */
  enquiryEmail?: string | null;
  metaTitleSuffix?: string | null;
  metaDescriptionFallback?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  ctaLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  newsletter?:
    | T
    | {
        heading?: T;
        body?: T;
        ctaLabel?: T;
        consentText?: T;
      };
  certifications?:
    | T
    | {
        title?: T;
        logo?: T;
        url?: T;
        id?: T;
      };
  legalLine?: T;
  legalLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  defaultOgImage?: T;
  legalName?: T;
  email?: T;
  phone?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        region?: T;
        postalCode?: T;
        country?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultCurrency?: T;
  enquiryEmail?: T;
  metaTitleSuffix?: T;
  metaDescriptionFallback?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'trips';
          value: number | Trip;
        } | null)
      | ({
          relationTo: 'destinations';
          value: number | Destination;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null);
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: number | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  tone: 'note' | 'tip' | 'warning';
  title?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TripCardBlock".
 */
export interface TripCardBlock {
  trip: number | Trip;
  layout: 'horizontal' | 'full';
  /**
   * Optional editorial line: "The one we recommend for first-timers."
   */
  note?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tripCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}