/* THIS FILE IS GENERATED BY PAYLOAD. */
/* Run `npm run generate:importmap` after adding or renaming any custom
   admin component (anything referenced by a `'@/path#Export'` string in
   the Payload config). Forgetting to regenerate is the usual cause of a
   blank panel or a "component not found" error in /admin. */

/** @type import('payload').ImportMap */
export const importMap = {}
